### ISSUE TITLE
Update Leaderboard to Display Potential Winnings Information

### ISSUE THREAD

**Issue by Cheelax** [z-korp/zkube#18]
Description:
We need to modify the Leaderboard component to incorporate buy-in amounts and display potential winnings for each player. This update will provide players with more comprehensive information about the game's economics and their potential rewards.

Tasks to accomplish:

1. Update Game Interface
    - Extend the Game interface to include a buyIn property
    - Create an ExtendedGame interface that includes potentialWinnings
2. Modify Content Component
    - Update the useMemo hook to calculate total buy-in and winning pool
    - Implement logic to distribute potential winnings (currently set as winner-takes-all)
    - Sort games based on score and combo, then assign potential winnings
3. Update Leaderboard Table
    - Add new columns for "Buy-In" and "Potential Winnings"
    - Adjust existing column widths to accommodate new information
4. Modify Row Component
    - Update the Row component to display buy-in and potential winnings for each player
    - Ensure proper formatting of numerical values (e.g., using toFixed(2) for currency)
7. Add Explanatory Information
    - Implement tooltips or info icons to explain how potential winnings are calculated (percentage for first, second, third and what's given to the studio
8. Testing
    - Test the leaderboard with various game scenarios to ensure correct calculations
    - Verify responsiveness on different screen sizes

Acceptance Criteria:

- Leaderboard displays accurate buy-in amounts for each player
- Potential winnings are correctly displayed
- The UI remains clean and easy to understand with the new information
- The leaderboard is responsive and displays correctly on all device sizes
- Users can easily understand how potential winnings are calculated

Please update this issue with any questions or suggestions for improving the implementation of buy-ins and potential winnings in the leaderboard.

**Comment by Oshioke-Salaki** [comment]
V

**Comment by kateberryd** [comment]
Hi @Cheelax I would love to work on this issue

**Comment by GoSTEAN** [comment]
@Cheelax Can I work on this issue?

**Comment by melnikga** [comment]
Hi, can I take this?
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hi zKube team,
I’m William from Costa Rica 🇨🇷 and member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as Full Stack engineer in several technologies (including the ones used on this project JS, and Typescript) and I am currently expanding my expertise in Rust, Cairo, and Solidity.

Profiles:
https://app.onlydust.com/u/wugalde19

https://github.com/wugalde19


### How I plan on tackling this issue
The way I’d approach this is by:
First, follow the Readme to set up the project locally.
Take a look at the Leaderboard component and understand the code to incorporate buy-in amounts and display potential winnings for each player as you guys request
Same with Content Component and Leaderboard Table
Follow the steps you described in the Tasks to accomplish: section and make a checklist with the acceptance criteria to make sure I complete all of those before sending a PR
Besides understanding and adding the requested changes I’ll go beyond and see if there’s any other improvement that can be done to the code itself.
I’ll be asking many questions in the Telegram channel to make sure I’m doing exactly what has been requested.
And finally, after your first review of that PR, take the feedback, iterate over my implementation based on the feedback that you guys provided, and at the end of the cycle deliver good quality code

**Comment by CollinsC1O** [comment]
Hi @Cheelax would love to be assigned this issue. Will love to work on this

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach the issue of modifying the Leaderboard component to incorporate buy-in amounts and display potential winnings for each player as follows:

1. **Update Game Interface**:
   a. I will extend the existing Game interface to include a `buyIn` property.
   b. I will create a new `ExtendedGame` interface that includes the `potentialWinnings` property.

2. **Modify Content Component**:
   a. I will update the `useMemo` hook in the Content component to calculate the total buy-in and winning pool.
   b. I will implement the logic to distribute the potential winnings, moving away from the current winner-takes-all approach.
   c. I will sort the games based on score and combo, then assign the potential winnings accordingly.

3. **Update Leaderboard Table**:
   a. I will add new columns for "Buy-In" and "Potential Winnings" in the Leaderboard table.
   b. I will adjust the existing column widths to accommodate the new information.

4. **Modify Row Component**:
   a. I will update the Row component to display the buy-in and potential winnings for each player.
   b. I will ensure proper formatting of numerical values (e.g., using `toFixed(2)` for currency).

5. **Add Explanatory Information**:
   a. I will implement tooltips or info icons to explain how the potential winnings are calculated, including the percentage distribution for first, second, third, and the studio's share.

6. **Testing and Validation**:
   a. I will thoroughly test the leaderboard with various game scenarios to ensure the calculations are correct.
   b. I will verify the responsiveness of the leaderboard on different screen sizes.
   c. I will ensure the UI remains clean and easy to understand with the new information.

7. **Documentation and Code Quality**:
   a. I will document the changes made to the Leaderboard component, including the new interfaces and the logic for calculating and distributing potential winnings.
   b. I will ensure the code is well-organized, maintainable, and follows the project's coding standards.

Throughout the implementation, I will collaborate with the team, gather feedback, and iterate on the design and functionality of the updated Leaderboard component to deliver a high-quality feature that provides players with comprehensive information about the game's economics and their potential rewards.

**Comment by Mario-Araya** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
I have extensive knowledge in frontend development, with a strong grasp of TypeScript, React, and Next.js. This background enables me to effectively contribute to complex projects by writing clean, maintainable code and leveraging modern frontend technologies to create dynamic and user-friendly interfaces.

### How I plan on tackling this issue
To implement the required updates to the Leaderboard component, I would first extend the Game interface to include the buyIn property and create an ExtendedGame interface that also includes potentialWinnings. Then, I would modify the Content component by updating the useMemo hook to calculate the total buy-in and winning pool, implementing a winner-takes-all logic for distributing potential winnings, and sorting the games accordingly. The Leaderboard table would be updated to include new columns for "Buy-In" and "Potential Winnings," with adjusted column widths. The Row component would be modified to display these new values, ensuring proper formatting for currency. Additionally, I would add tooltips or info icons to explain the calculation of potential winnings. Finally, I would thoroughly test the leaderboard with various game scenarios to verify that all calculations are correct, the UI remains clean and responsive across different screen sizes, and users can easily understand the new information.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hi @Cheelax

I’m ready to work on modifying the Leaderboard component to incorporate buy-in amounts and display potential winnings for each player. My name is Benjamin, and I have extensive experience building gamified TypeScript projects, specializing in Next.js, TypeScript, and frontend development. I’ve contributed to various projects, including those on OnlyDust, where I tackled complex UI and component challenges.

### Understanding the Issue
The Leaderboard currently lacks detailed information about buy-in amounts and potential winnings. By incorporating these elements, players will gain a clearer understanding of the game’s economics and their potential rewards.


### How I plan on tackling this issue
#### Update Game Interface
- **Extend Game Interface**: I will add a `buyIn` property to the existing Game interface.
- **Create ExtendedGame Interface**: I will introduce an `ExtendedGame` interface to include `potentialWinnings`.

#### Modify Content Component
- **Update useMemo Hook**: I will update the `useMemo` hook to calculate the total buy-in and winning pool.
- **Distribution Logic**: I will implement logic to distribute potential winnings, initially set as winner-takes-all.
- **Sorting and Assignment**: I will sort games based on score and combo, then assign potential winnings accordingly.

#### Update Leaderboard Table
- **New Columns**: I will add new columns for "Buy-In" and "Potential Winnings."
- **Adjust Layout**: I will adjust existing column widths to fit the new information.

#### Modify Row Component
- **Display Information**: I will update the Row component to show buy-in amounts and potential winnings for each player.
- **Formatting**: I will ensure numerical values are formatted properly, e.g., using `toFixed(2)` for currency.

#### Add Explanatory Information
- **Tooltips/Info Icons**: I will implement tooltips or info icons to explain how potential winnings are calculated, including percentages for positions and allocations to the studio.

#### Testing
- **Leaderboard Scenarios**: I will test the leaderboard with various game scenarios to ensure accurate calculations.
- **Responsiveness**: I will verify that the leaderboard displays correctly across different screen sizes.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hello @Cheelax I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/ and https://metacrypt.vercel.app/ showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.



### How I plan on tackling this issue
I will ensure that the criteria are met by updating the leader board to display potential winnings

**Comment by Cheelax** [comment]
Hi everyone.
There is a new process for the ODHack, now you must apply to the tasks directly from Onlydust: https://app.onlydust.com/hackathons/odhack-70
We will only look at application made via this process.
